# Generated by Django 4.2.9 on 2024-01-21 14:22

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_of_servings', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('main_image', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('preparation_time', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_preparation_time', message='Preparation time must be in the format HH:MM:SS.', regex='^\\d+:\\d+:\\d+$')])),
                ('instructions', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
