version: '3'
services:
  postgresdb:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: CookyRecipe123
      POSTGRES_USER: cookyadmin
      POSTGRES_DB: cookyrecipe
    ports:
      - "5433:5432"
    networks:
      - cooky_recipe_apis
    volumes:
      - pgdata:/var/lib/postgresql/data/

  cooky:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cooky_recipe_apis
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgresdb
    networks:
      - cooky_recipe_apis

networks:
  cooky_recipe_apis:

volumes:
  pgdata:
